maclaurinStock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maclaurinStock_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)
# ]+ static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

maclaurinStock_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', main, name='main'),
    path('', about, name='about'),
    path('', staff, name='staff'),
    path('.well-known/acme-challenge/<slug:id>', ssl, name='ssl'),
]

maclaurinStock_setting/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
]

maclaurinStock_app/models.py
from maclaurinStock_setting.models import *

# Create your models here.
class Strategy(CommonInfo):
    name = models.ForeignKey(StrategyNameGroup, to_field='strategy_name', db_column='name', on_delete=models.CASCADE)
    description = models.CharField(max_length=max_length)
    profit_rate = models.DecimalField(decimal_places=decimal_places, max_digits=max_digits)
    from_date = models.DateField()
    to_date = models.DateField()
    strategy_image = models.ImageField(upload_to=f'%Y/%m/%d', blank=True, null=True)
    strategy_detail_image = models.ImageField(upload_to=f'%Y/%m/%d', blank=True, null=True)
    stock_image = models.ImageField(upload_to=f'%Y/%m/%d', blank=True, null=True)

class StrategyCost(CommonInfo):
    name = models.ForeignKey(StrategyNameGroup, to_field='strategy_name', db_column='name',  on_delete=models.CASCADE)
    group = models.ForeignKey(StrategyCostGroup, to_field='strategy_cost', db_column='group', on_delete=models.CASCADE)
    cost = models.BigIntegerField()

class Staff(CommonInfo):
    name = models.CharField(unique=True, max_length=max_length)
    description = models.TextField()
    image = models.ImageField(upload_to=f'%Y/%m/%d', blank=True, null=True)

class Contract(CommonInfo):
    name = models.CharField(max_length=max_length)
    contract_num = models.TextField()

maclaurinStock_setting/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin, AbstractBaseUser
from django.urls import reverse
from django.utils import timezone

# Create your models here.
decimal_places = 2
max_digits = 20
max_length = 255
ignore_field = set(["created_by", "updated_at", "updated_by", "created_at", "status"])

def makeModelString(self):
    field_values = []
    for field in self._meta.get_fields():
        try:
            field_name = field.attname
            if field_name in ignore_field:
                continue
            field_values.append(str(self.__getattribute__(field.attname)))
        except:
            pass
    return '-'.join(field_values)


class CommonInfo(models.Model):
    created_by = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_by = models.TextField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)

    STATUS_CHOICE = (
        # (CODE, "DESCRIPTION"),
        (2, "Update"),
        (1, "Pending Updated"),
        (0, "Done"),
        (-1, "Pending Deleted"),
        (-2, "Delete"),
    )
    status = models.IntegerField(choices=STATUS_CHOICE, default=0)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(CommonInfo, self).save(*args, **kwargs)

    def __str__(self):
        return makeModelString(self)

    class Meta:
        abstract = True

class StrategyNameGroup(models.Model):
    strategy_name = models.CharField(primary_key=True, unique=True, max_length=max_length)

class StrategyCostGroup(models.Model):
    strategy_cost = models.CharField(primary_key=True, unique=True, max_length=max_length)

maclaurinStock_app/views.py
from django.shortcuts import render
from django.db.models import *
from .models import *
from django.template.response import TemplateResponse
import functools
from django.shortcuts import reverse
import datetime
from django.http import JsonResponse
# Create your views here.
def navsDecorator(function):
    @functools.wraps(function)
    def wrapper(*args, **kwargs):
        getNav = lambda url, name, *args, **kwargs:{"url":reverse(url, kwargs=kwargs), "name": name, 'url_name':url, 'kwargs':kwargs}
        template = function(*args, **kwargs)
        try:
            navs = [
                getNav('main','상품 소개'),
                getNav('about','서비스 소개'),
                getNav('staff','멤버'),
            ]
            template.context_data['navs'] = navs
            return template.render()
        except Exception as e:
            print(e)
            return template
    return wrapper

@navsDecorator
def main(req):
    if req.method == 'GET':
        sections = Strategy.objects.filter(status=0).values()
        for section in sections:
            costs = StrategyCost.objects.filter(status=0).values('cost', 'group').filter(name = section['name_id'])
            section['costs'] = []
            for cost in costs:
                section['costs'].append({'cost':cost['cost'], 'group':cost['group']})
            section['total_date'] = section['to_date'] - section['from_date']
        return TemplateResponse(req, template='main.html', context={'sections': sections}, status=302)
    elif req.method == 'POST':
        try:
            data = req.POST.copy()
            data = {key:val for key, val in data.items()}
            Contract(**data).save()
            res = JsonResponse({'msg': "제출 되었습니다\n연락 드리겠습니다"})
            res.status_code = 200
            return res
        except:
            res = JsonResponse({'msg': f"입력실패", 'detail': f"입력실패"})
            res.status_code = 400
            return res


@navsDecorator
def about(req):
    return TemplateResponse(req, template='about.html', context={}, status=302)

@navsDecorator
def staff(req):
    sections = Staff.objects.filter(status=0).values()
    return TemplateResponse(req, template='staff.html', context={'sections': sections}, status=302)

def ssl(req, id):
    return TemplateResponse(req, template='ssl', context={})

maclaurinStock_setting/views.py
from django.shortcuts import render
from django.db.models import *

# Create your views here.

templates/about.html
{% extends "index.html" %}
{% load static %}
<!-- main contents -->
{% block contents %}
<div class="contents_area">
    <dl class="algo_subject">
        <dt>서비스 소개</dt>
        <dd>안정성과 수익률이 좋은 알고리즘을 엄선하여 소개합니다.</dd>
    </dl>
    <!-- 추천 알고리즘 영역 -->
    <div class="algo_area">
        <h1>맥클로린 로봇어드바이징 서비스는 코스피, 코스닥과 같은 주식 분야와 해외선물 분야 ( 원자재, 미국 지수 )에서 자산의 매입과 매도  시점을 지원하여, 전문지식이 부족한 투자자, 위험회피자가 매입, 매도하는 성과보다 더 좋은 성과를 창출하는 것을 목표로 하고 있습니다.
</h1><h1>
누가 사용할까요?
맥클로린 로봇어드바이징 서비스는 지금은 3개 이상의 자산운용, 헷지펀드, 제조 기업 고객사 / 50명 이상의 개인 투자자들이 이용하고 있습니다.
</h1>

    </div>
    <!-- //추천 알고리즘 영역 -->
    <ul class="sub_contents">
        <li><img src="{% static 'imgs/guide_img.jpg' %}" alt=""></li>
        <li><img src="{% static 'imgs/companies.gif' %}" alt="stock firms"></li>
    </ul>
    <!-- mobile -->
    <ul class="sub_mob">
        <li><img src="{% static 'imgs/guide_mob_img.jpg' %}" alt=""></li>
        <li><img src="{% static 'imgs/companies_mob.gif' %}" alt="stock firms"></li>
    </ul>
    <!-- //mobile -->
</div>
{% endblock contents %}

templates/index.html
<!doctype html>
<html>
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="imagetoolbar" content="no" />
    <meta name="keywords" content="" />
    <meta name="title" content="" />
    <meta name="description" content="" />
    <meta name="robots" content="index,follow" />
    <title>MACLAURIN - Home</title>
    <link href="{% static 'class/css/mac.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'class/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'class/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'class/css/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'class/css/jquery-ui.structure.min.css' %}" rel="stylesheet">
    <link href="{% static 'class/css/jquery-ui.theme.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <noscript><link rel="stylesheet" href="{% static 'class/css/noscript.css' %}" /></noscript>
    <script type="text/javascript" src="{% static 'class/js/jquery-1.8.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'class/js/selectbox-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'class/js/bootstrap-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'class/js/notify.min.js' %}"></script>
    <!--<script type="text/javascript" src="{% static 'class/js/jquery.min.js' %}"></script>-->
    <script type="text/javascript" src="{% static 'class/js/jquery-ui.min.js' %}"></script>
    <!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $(function () {
                $("select").each(function(){
                    $(this).selectbox();
                })
            });
        });
    </script>
    <!--[if lt IE 9]>
    <script src="{% static 'class/js/html5shiv.min.js' %}"></script>
    <script src="{% static 'class/js/respond.js' %}"></script>
    <script src="{% static 'class/js/respond.min.js' %}"></script>
    <![endif]-->
</head>

<body>
<!-- gnb top -->
<div id="gnbTop">
    <div class="info_menu">
        <ul class="info_link">
            <!--<li><a href="#">로그인</a></li>-->
            <!--<li><a href="#">회원가입</a></li>-->
            <!--<li><a href="#">고객지원</a></li>-->
        </ul>
    </div>
</div>
<!-- //gnb top -->
<!-- gnb -->
<header id="headerWrap">
    <div class="header">
        <h1 class="logo_h"><img src="{% static 'imgs/logo_h.png' %}" alt="MACLAURIN" onclick="javascript:location.href='/';"/></h1>
        <nav role="navigation">
            <ul class="main_menu">
                {% for nav in navs %}
                    <li><a href="{{ nav.url }}">{{ nav.name }}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</header>
<!-- //gnb -->
<!-- mob. gnb -->
<div class="nav_wrapper">
    <div class="spinner-master"><input type="checkbox" id="spinner-form" />
        <label for="spinner-form" class="spinner-spin">
            <div class="spinner diagonal part-1"></div>
            <div class="spinner horizontal"></div>
            <div class="spinner diagonal part-2"></div></label></div>
    <nav id="menu" class="menu">
        <ul class="dropdown">
                {% for nav in navs %}
                    <li><a href="{{ nav.url }}">{{ nav.name }}</a></li>
                {% endfor %}
        </ul>
    </nav>
</div>
<script type="text/javascript" src="{% static 'class/js/m_gnb.js' %}"></script>
<header id="mobNav"><h1><a href="/"><img src="{% static 'imgs/logo_h.png' %}" alt="MACLAURIN" /></a></h1></header>
<!-- //mob. gnb-->
<!-- main visual -->
<div class="visual">
    {% block visual %}
    {% endblock visual %}
</div>
<!-- //main visual -->
<div id="contentsWrap">
    {% block contents %}
    {% endblock contents %}
</div>
<footer id="footer">
    {% block footer %}
	<div class="footer_inner">
		<a class="footer_logo"><img src="{% static 'imgs/logo_f.png' %}" alt="MACLAURIN"></a>
		<address>
			<span>서울시 강남구 언주로647 (강남빌딩) 4층</span>
			<p class="copyright">COPYRIGHT &copy; MACLAURIN ALL RIGHTS RESERVED.</p>
		</address>
	</div>
		<div id="csBannerFixed">
			<a href="//bt1s.kr/a.katalk" target="_blank">
				<img src="{% static 'imgs/katalk.png' %}" alt="카카오톡 문의">
			</a>
		</div>
    {% endblock footer %}
</footer>
<!-- SCRIPT -->
<script>
    if(typeof document.compatMode!='undefined'&&document.compatMode!='BackCompat'){
        csFixedRBCalc="_top:expression(document.documentElement.scrollTop+document.documentElement.clientHeight-this.clientHeight-5);_left:expression(document.documentElement.scrollLeft + document.documentElement.clientWidth - offsetWidth);}";
    }else{
        csFixedRBCalc="_top:expression(document.body.scrollTop+document.body.clientHeight-this.clientHeight-5);_left:expression(document.body.scrollLeft + document.body.clientWidth - offsetWidth);}";
    }
    var csBannerFixed='#csBannerFixed{border 1 solid;position:fixed;_position:absolute;bottom:0px;right:0px;overflow:hidden;z-index:100;' + csFixedRBCalc;
    document.write( '<STYLE TYPE="text/css">'+csBannerFixed+'</STYLE>');
</script>
<script>
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                // Only send the token to relative URLs i.e. locally.
                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
            }
        }
    });
</script>
{% block js %}
{% endblock js %}
<!-- //SCRIPT -->
</html>

templates/main.html
{% extends "index.html" %}
{% load static %}
<!-- main contents -->
{% block contents %}
{% load humanize %}
<div class="contents_area">
    <dl class="algo_subject">
        <!--<dt>추천 알고리즘</dt>-->
        <!--<dd>안정성과 수익률이 좋은 알고리즘을 엄선하여 소개합니다.</dd>-->
        <dt>추천 전략</dt>
        <dd>10년 이상 장기간 검증된 안정성과 수익률이 좋은 전략을 엄선하여 소개합니다.</dd>
    </dl>
    <!-- 추천 알고리즘 영역 -->
    <div class="algo_area">
        <!-- 전략섹션 출력 -->
        {% for section in sections %}
        <section class="algo_section">
            <span class="section_view"><a href="#" data-toggle="modal" data-target="#myModal"><img class="img_over" src="media/{{section.strategy_detail_image}}" alt="상세보기"><img class="img_up" src="media/{{section.strategy_image}}" alt="전략소개"></a></span>
            <dl class="strategy_intro">
                <dt>{{ section.name_id }}</dt>
                <dd>{{ section.description }}</dd>
            </dl>
            <div class="graph_area">
                <dl>
                    <dt>{{ section.profit_rate }} %</dt>
                    <dd><time datetime="{{ section.to_date }}">{{ section.to_date|date:"Y-m-d" }}</time> ({{ section.total_date.days }}일)</dd>
                </dl>
            </div>
            <div class="btn_payment">
                <a href="#"><img src="{% static 'imgs/btn_payment_general.png' %}" alt="일반결제"></a>
                <a href="#"><img src="{% static 'imgs/btn_payment_regular.png' %}" alt="정기결제"></a>
            </div>
            <p class="select_field">
                <select name="payment_select" id="payment_select1">
                    {% for cost in section.costs %}
                        <option value="{{ cost.group }}"><strong>{{ cost.cost|intcomma }}원</strong> ({{ cost.group }})</option>
                    {% endfor %}
                </select>
            </p>
            <span class="btn_buy"><a href="//bt1s.kr/a.strategy_{{ section.id }}" target="_blank"><button class="buttonBuy1">구매하기</button></a></span>
        </section>
        {% endfor %}
        <!-- //전략섹션 출력 -->
    </div>
    <!-- //추천 알고리즘 영역 -->
    <ul class="sub_contents">
        <li><a role="button" data-toggle="modal" data-target="#myModal"><img src="{% static 'imgs/guide_img_origin.jpg' %}" alt=""></a></li>
        <!--<li><a role="button" data-toggle="modal" data-target="#myModal"><img src="{% static 'imgs/guide_mob_img.jpg' %}" alt=""></a></li>-->
        <!--<li class="section_view"><a href="#"><img class="img_over" src="{% static 'imgs/guide_img_origin.jpg' %}" alt="상세보기"><img class="img_up" src="{% static 'imgs/guide_img.jpg' %}" alt="전략소개"></a><</li>-->
        <li><img src="{% static 'imgs/companies.gif' %}" alt="stock firms"></li>
    </ul>
    <!-- mobile -->
    <ul class="sub_mob">
        <li><button data-toggle="modal" data-target="#myModal"><img src="{% static 'imgs/guide_mob_img_origin.jpg' %}" alt=""></button></li>
        <!--<li><button data-toggle="modal" data-target="#myModal"><img src="{% static 'imgs/guide_mob_img.jpg' %}" alt=""></button></li>-->
        <!--<span class="section_view"><a href="#"><img class="img_over" src="/media/{{ section.image }}" alt="상세보기"><img class="img_up" src="/media/{{ section.image }}" alt="전략소개"></a></span>-->
        <li><img src="{% static 'imgs/companies_mob.gif' %}" alt="stock firms"></li>
    </ul>
    <!-- //mobile -->
</div>
{% include "modal.html" %}
{% endblock contents %}

templates/modal.html
    <!-- modal 구동 버튼 (trigger) -->
    <!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">-->
        <!--Modal 띄우기-->
    <!--</button>-->

    <!-- Modal -->
    <div id="myModal" class="modal fade bd-example-modal" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title" id="myModalLabel">주식카톡방 무료 예약</h1>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <!-- FORM -->
                    <form id="id_form_contract" name="form_contract" class="horizontal">
                            <div class="form-group">
                                <label for="id_name" class="col-xs-6 control-label">성함</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="name" id="id_name" placeholder="Your Name" data-placement="top" required autofocus>
                                </div>
                            </div>

                            <!--<div class="form-group">-->
                                <!--<label for="textArea" class="col-xs-6 control-label">Address</label>-->
                                <!--<div class="col-lg-10">-->
                                    <!--<textarea class="form-control" rows="3" name="textAddress" id="textAddress" placeholder="Your Address"></textarea>-->
                                <!--</div>-->
                            <!--</div>-->

                            <!--<div class="form-group">-->
                                <!--<label for="inputlName" class="col-xs-6 control-label">Email</label>-->
                                <!--<div class="col-sm-10">-->
                                    <!--<input type="text" class="form-control" name="inputREmail" id="inputREmail" placeholder="email@you.com" required>-->
                                <!--</div>-->
                            <!--</div>-->

                            <div class="form-group">
                                <label for="id_contract_num" class="col-xs-6 control-label">연락처</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="contract_num" id="id_contract_num" placeholder="01X-XXX-XXXX" required>
                                </div>
                            </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button id="id_submit_contract" name="submit_contract" type="button" class="btn btn-primary" data-dismiss="modal">제출</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('#id_submit_contract').on('click', function(){
            $.ajax({
            type: "POST",
            url: window.location.pathname,
            data: $('#id_form_contract').serialize(),
            async: false,
            success: function (res) {
              $.notify(res.msg, "제출되었습니다", "info");
            },
            error: function (res) {
              is_continuous = false;
              $.notify(
                "Data Failed \n" + res.detail,
                "danger"
              );
            },
          });
        })
    </script>

templates/staff.html
{% extends "index.html" %}
{% load static %}
<!-- main contents -->
{% block contents %}
<div class="contents_area">
    <dl class="algo_subject">
        <dt>추천 알고리즘</dt>
        <dd>안정성과 수익률이 좋은 알고리즘을 엄선하여 소개합니다.</dd>
    </dl>
    <!-- 스태프 영역 -->
    <div class="algo_area">
        <!-- 스태프 출력 -->
        {% for section in sections %}
        <section class="algo_section">
            <span class="section_view"><a href="#"><img class="img_over" src="/media/{{ section.image }}" alt="상세보기"><img class="img_up" src="/media/{{ section.image }}" alt="전략소개"></a></span>
            <dl class="strategy_intro">
                <dt>[{{ section.name }}]</dt>
                <dd>{{ section.description }}</dd>
            </dl>
        </section>
        {% endfor %}
        <!-- //전략섹션 출력 -->
    </div>
    <!-- //추천 알고리즘 영역 -->
    <ul class="sub_contents">
        <li><img src="{% static 'imgs/guide_img.jpg' %}" alt=""></li>
        <li><img src="{% static 'imgs/companies.gif' %}" alt="stock firms"></li>
    </ul>
    <!-- mobile -->
    <ul class="sub_mob">
        <li><img src="{% static 'imgs/guide_mob_img.jpg' %}" alt=""></li>
        <li><img src="{% static 'imgs/companies_mob.gif' %}" alt="stock firms"></li>
    </ul>
    <!-- //mobile -->
</div>
{% endblock contents %}

templates/staff_modal.html
<!-- Modal -->
<div class="modal fade" id="staffModalCenter" tabindex="-1" role="dialog" aria-labelledby="staffModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staffModalCenterLongTitle">{{ section.name }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="avatar"><img src="{% section.image %}"</div>
      <div class="modal-body">
        {{ section.description }}
      </div>
      <!--<div class="modal-footer">-->
        <!--<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>-->
        <!--<button type="button" class="btn btn-primary">Save changes</button>-->
      <!--</div>-->
    </div>
  </div>
</div>